// Build the Phase-1 indexed-Merkle non-membership circuits (the-reduction.md S4.1):
// compile at IMT depths 16 / 20 / 24, Groth16 setup, and emit a constraint-count
// + crossover report to docs/self-audit/nonmembership_imt.md.
//   node scripts/build_nonmembership_imt.mjs
// Reuses build/pot15_final.ptau (2^15 = 32768 constraint capacity; the deepest
// variant here is ~13.5k).

import { execFileSync } from "child_process";
import { copyFileSync, rmSync, existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { randomBytes } from "crypto";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { createRequire } from "module";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
process.chdir(ROOT);
const require = createRequire(import.meta.url);
const NODE = process.execPath;
const CIRCOM2 = require.resolve("circom2/cli.js");
const SNARKJS = join(dirname(require.resolve("snarkjs")), "cli.cjs");
const run = (args, opts = {}) => execFileSync(NODE, args, { stdio: "inherit", ...opts });
const capture = (args, opts = {}) => execFileSync(NODE, args, { encoding: "utf8", ...opts });
const seed = () => randomBytes(24).toString("hex");

const PTAU = "build/pot15_final.ptau";
if (!existsSync(PTAU)) { console.error("build/pot15_final.ptau missing -- run scripts/build.mjs first"); process.exit(1); }

const DEPTHS = [16, 20, 24];
const CIRCUITS = DEPTHS.map((d) => ({
  depth: d,
  name: `wedge_mem_w8_d9_split_revimt${d}`,
  src: `main_mem_w8_d9_split_revimt${d}`,
}));

// clean stale circom artifacts
for (const f of readdirSync("circuits")) {
  if (f.endsWith("_js")) rmSync(join("circuits", f), { recursive: true, force: true });
  if (/main_mem_w8_d9_split_revimt\d+\.(r1cs|sym)$/.test(f)) rmSync(join("circuits", f), { force: true });
}

const info = {};
for (const c of CIRCUITS) {
  console.log(`\n== compiling ${c.src} (IMT depth ${c.depth}) ==`);
  run([CIRCOM2, `${c.src}.circom`, "--r1cs", "--wasm", "--sym", "--O2", "-o", ".",
       "-l", ".", "-l", "../node_modules/circomlib/circuits"], { cwd: join(ROOT, "circuits") });
  copyFileSync(join("circuits", `${c.src}.r1cs`), join("build", `${c.name}.r1cs`));
  copyFileSync(join("circuits", `${c.src}_js`, `${c.src}.wasm`), join("build", `${c.name}.wasm`));

  const out = capture([SNARKJS, "r1cs", "info", `build/${c.name}.r1cs`]);
  const grab = (re) => Number((out.match(re) || [])[1]);
  info[c.name] = {
    depth: c.depth,
    constraints: grab(/# of Constraints:\s*(\d+)/),
    wires: grab(/# of Wires:\s*(\d+)/),
    publicInputs: grab(/# of Public Inputs:\s*(\d+)/),
    privateInputs: grab(/# of Private Inputs:\s*(\d+)/),
    publicOutputs: grab(/# of Outputs:\s*(\d+)/),
  };

  console.log(`\n== groth16 setup ${c.name} ==`);
  run([SNARKJS, "groth16", "setup", `build/${c.name}.r1cs`, PTAU, `build/${c.name}_0.zkey`]);
  run([SNARKJS, "zkey", "contribute", `build/${c.name}_0.zkey`, `build/${c.name}_final.zkey`, "--name=phase1-imt", `-e=${seed()}`]);
  run([SNARKJS, "zkey", "export", "verificationkey", `build/${c.name}_final.zkey`, `build/${c.name}_vkey.json`]);
  rmSync(`build/${c.name}_0.zkey`, { force: true });
}

// ---- report -----------------------------------------------------------------
const BASE = 4309; // wedge_mem_w8_d9_split (CIRCUIT-FREEZE.md)
const rows = CIRCUITS.map((c) => {
  const k = info[c.name];
  const added = k.constraints - BASE;
  return { ...c, ...k, added };
});
// linear model added(depth) = fixed + perLevel*depth  from the two extreme depths
const d0 = rows[0], d2 = rows[rows.length - 1];
const perLevel = (d2.added - d0.added) / (d2.depth - d0.depth);
const fixed = d0.added - perLevel * d0.depth;

const revList = { 64: 64, 256: 256, 1024: 1024 }; // measured: NonMembershipList adds exactly R

let md = `# Phase 1 — indexed Merkle non-membership: constraint report\n\n`;
md += `_Generated by \`scripts/build_nonmembership_imt.mjs\`. Source: the-reduction.md §4.1._\n\n`;
md += `Base circuit \`wedge_mem_w8_d9_split\` = **${BASE}** constraints (CIRCUIT-FREEZE.md).\n`;
md += `Toolchain: circom2 0.2.23 / circomlib 2.0.5 / snarkjs 0.7.6, \`--O2\`.\n\n`;
md += `## Indexed Merkle tree (IMT) non-membership — cost is independent of revoked-set size R\n\n`;
md += `| IMT depth | capacity (max revocations) | total constraints | added over base | nPublic |\n`;
md += `|---:|---:|---:|---:|---:|\n`;
for (const r of rows) {
  md += `| ${r.depth} | 2^${r.depth} = ${(1 << r.depth).toLocaleString()} | **${r.constraints.toLocaleString()}** | +${r.added.toLocaleString()} | ${r.publicInputs + r.publicOutputs} |\n`;
}
md += `\nLinear model for the added cost: **added(depth) ≈ ${Math.round(fixed).toLocaleString()} + ${Math.round(perLevel)}·depth** `;
md += `(per-level = one Poseidon(2) path hash; fixed = one Poseidon(3) leaf hash + two full-width 254-bit field comparisons + range checks).\n\n`;
md += `## Current approach: \`NonMembershipList(R)\` — exactly R constraints, plus R public inputs\n\n`;
md += `| variant | R | total constraints | added over base | nPublic |\n`;
md += `|---|---:|---:|---:|---:|\n`;
md += `| wedge_mem_w8_d9_split_rev64 | 64 | 4373 | +64 | 71 |\n`;
md += `| wedge_mem_w8_d9_split_rev256 | 256 | 4565 | +256 | 263 |\n`;
md += `| wedge_mem_w8_d9_split_rev1024 | 1024 | 5333 | +1024 | 1031 |\n\n`;
md += `## Crossover (raw constraint count)\n\n`;
md += `The IMT is cheaper than the list once **R > (added constraints at that depth)**:\n\n`;
md += `| IMT depth | crossover R |\n|---:|---:|\n`;
for (const r of rows) md += `| ${r.depth} | ~${r.added.toLocaleString()} |\n`;
md += `\nBelow the crossover the brute-force list wins on raw R1CS size; above it the IMT is not merely cheaper but the only option that stays bounded. The list also adds **R public inputs** (the verifier ships R field elements every verification); the IMT adds **one** (\`revRoot\`), so by verifier bandwidth and by proof/verification key size the IMT dominates well before the raw-constraint crossover.\n\n`;
md += `## Recommended deployment\n\n`;
md += `IMT **depth 20** (capacity ~1.05M revocations): total **${info["wedge_mem_w8_d9_split_revimt20"].constraints.toLocaleString()}** constraints, constant in R, constant nPublic. This replaces the rev64/rev256/rev1024 circuit family with a single circuit whose cost does not grow with the revocation list.\n`;

writeFileSync("docs/self-audit/nonmembership_imt.md", md);
writeFileSync("docs/self-audit/nonmembership_imt.json", JSON.stringify({ base: BASE, model: { fixed, perLevel }, rows }, null, 2));
console.log("\nreport -> docs/self-audit/nonmembership_imt.md");
console.log("next   -> node scripts/test_nonmembership_imt.mjs");
