// ===========================================================================
// Multi-point two-witness search        (after-the-oracle.md, Task 1)
//
//   node scripts/two_witness_multipoint.mjs [--dir build/multipoint]
//        [--r1cs F] [--wasm F] [--sym F] [--maxfill N] [--json OUT]
//
// WHY.  The single-point tool computes the Jacobian null space at ONE honest
// witness. The rank of a non-linear R1CS Jacobian can vary across the solution
// manifold: a signal determined at one point may be free at another. One point
// is measure zero. This driver re-runs the exact same analysis at every witness
// in --dir (generated by gen_input_multipoint.mjs: leftmost / rightmost /
// max-depth / alternating / random path shapes x zero / one / max / random /
// alternating sibling vectors x random + field-edge s, ctx, epochAction,
// epochTree, signalHash) and reports:
//
//   * nullity at every point                        -> is it stably 9 ?
//   * the SUPPORT of the null space at every point  -> does it move ?
//   * any null-space direction that moves a PUBLIC output at ANY point
//     -> STOP: that is a real soundness bug in the deployed circuit.
//   * the "spectrum" question, handled honestly for an exact F_p computation
//     (see SPECTRUM NOTE below).
//
// SPECTRUM NOTE.  "Singular-value spectrum" is a real/complex-analysis notion.
// The R1CS Jacobian here is a matrix over the BN254 scalar field; its rank is
// EXACT -- a column is in the span or it is not, there is no "nearly zero"
// singular value. A floating-point SVD would require lifting entries whose
// balanced magnitude is ~2^253 (hash-output coefficients a_k, b_k) into the
// reals, where the result is dominated by that scale and carries no signal.
// So this driver does NOT fabricate an SVD. The finite-field analogue of a
// "near-degenerate determination" is a pivot that is non-zero only because of
// a specific witness value rather than circuit structure; the decisive test
// for that is precisely multi-point stability of the exact rank, plus a
// per-pivot classification (structural coefficient vs witness-dependent
// coefficient) reported below. If the exact nullity is identical across dozens
// of structurally diverse points and every null vector is exactly zero on
// every public column at every point, there is no near-degeneracy to find.
// ===========================================================================

import { readFileSync, existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import * as snarkjs from "snarkjs";
import {
  P, mod, addm, subm, mulm,
  readR1CS, symMap, dot, rowEchelon, nullspaceBasis,
} from "./two_witness_search.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const A = process.argv.slice(2);
const opt = (n, d) => { const i = A.indexOf(`--${n}`); return i >= 0 && A[i + 1] ? A[i + 1] : d; };
const DIR = opt("dir", join(ROOT, "build", "multipoint"));
const R1CS = opt("r1cs", join(ROOT, "build", "wedge_mem_w8_d9_split.r1cs"));
const WASM = opt("wasm", join(ROOT, "build", "wedge_mem_w8_d9_split.wasm"));
const SYM = opt("sym", join(ROOT, "build", "main_mem_w8_d9_split.sym"));
const MAXFILL = parseInt(opt("maxfill", "800"), 10);
const JSON_OUT = opt("json", join(ROOT, "docs", "self-audit", "two_witness_multipoint.json"));

// repo-relative POSIX path — never emit an absolute machine path into an artifact
const relPath = (p) => String(p).replace(ROOT, "").replace(/\\/g, "/").replace(/^\/+/, "") || String(p);
// balanced representative of a field element, as a bigint in (-P/2, P/2]
const bal = (x) => { x = mod(x); return x > P / 2n ? x - P : x; };
const isStructuralCoeff = (v) => { const a = bal(v); const m = a < 0n ? -a : a; return m <= 64n; };

async function witnessFor(inputPath) {
  const input = JSON.parse(readFileSync(inputPath, "utf8"));
  const wpath = join(tmpdir(), `twmp_${process.pid}_${Math.random().toString(36).slice(2)}.wtns`);
  await snarkjs.wtns.calculate(input, WASM, wpath);
  return (await snarkjs.wtns.exportJson(wpath)).map((x) => mod(BigInt(x)));
}

function analyseAtWitness(r, w1, FREE, FIXED, idx2name, isPublic) {
  // honest witness must satisfy every constraint
  for (const c of r.cons) {
    if (subm(mulm(dot(c.a, w1), dot(c.b, w1)), dot(c.c, w1)) !== 0n) {
      return { ok: false, reason: "honest witness violates the R1CS" };
    }
  }
  // Jacobian rows at w1 over FREE columns
  const jrows = r.cons.map((c) => {
    const a = dot(c.a, w1), b = dot(c.b, w1);
    const row = new Map();
    const add = (i, v) => { const nv = addm(row.get(i) ?? 0n, v); if (nv === 0n) row.delete(i); else row.set(i, nv); };
    for (const [i, v] of c.b) add(i, mulm(a, v));
    for (const [i, v] of c.a) add(i, mulm(b, v));
    for (const [i, v] of c.c) add(i, mod(-v));
    for (const i of [...row.keys()]) if (FIXED.has(i)) row.delete(i);
    return row;
  });

  let ech;
  try { ech = rowEchelon(jrows, FREE, { maxFill: MAXFILL }); }
  catch (e) { return { ok: false, reason: `elimination aborted: ${e.message}` }; }

  const nullity = FREE.length - ech.rank;
  const basis = nullspaceBasis(FREE, ech);

  // support: every signal carrying non-zero mass in any null-space basis vector
  const support = new Set();
  for (const { vec } of basis) for (const [c, v] of vec) if (v !== 0n) support.add(c);

  // exact leakage check: does ANY null vector have a non-zero entry on ANY
  // public column?  (public outputs are indices 1..nPubOut; every input is FIXED)
  const publicMovers = [];
  const nonPublicDirs = [];
  const killedDirs = [];
  for (const { freeCol, vec } of basis) {
    const w2 = w1.slice();
    for (const [c, v] of vec) w2[c] = mod(w1[c] + v);
    let viol = 0;
    for (const c of r.cons) if (subm(mulm(dot(c.a, w2), dot(c.b, w2)), dot(c.c, w2)) !== 0n) viol++;
    const changed = [...vec.keys()].map((c) => idx2name.get(c) || `w[${c}]`);
    if (viol > 0) { killedDirs.push({ anchor: idx2name.get(freeCol) || `w[${freeCol}]`, viol }); continue; }
    const pub = [...vec.keys()].filter(isPublic).map((c) => idx2name.get(c) || `w[${c}]`);
    if (pub.length) publicMovers.push({ anchor: idx2name.get(freeCol) || `w[${freeCol}]`, pub, changed });
    else nonPublicDirs.push(changed);
  }

  // per-carrier "spectrum" analogue: for each support signal, find the pivot row
  // that eliminates it and classify its ORIGINAL Jacobian coefficient.
  const carrierClass = [];
  for (const cCol of support) {
    // Is this carrier column ever non-zero in the Jacobian? If it is identically
    // zero across every row, the signal is STRUCTURALLY free (an exact zero
    // column) -- the strongest, least ambiguous form of "under-determined", and
    // the F_p statement that there is no near-degenerate / marginal
    // determination here at all. If it does appear, classify the first pivot
    // coefficient: a structural constant is robust; a witness-dependent value
    // being non-zero is the finite-field analogue of a near-zero singular value.
    let cls = "structurally-free (zero column in J)";
    for (const row of jrows) {
      const v = row.get(cCol);
      if (v !== undefined && v !== 0n) { cls = isStructuralCoeff(v) ? "structural-coeff" : "witness-dependent-coeff"; break; }
    }
    carrierClass.push({ signal: idx2name.get(cCol) || `w[${cCol}]`, pivotCoeff: cls });
  }

  // exact off-public magnitude: largest |entry| of any null vector on a public col
  let maxPubEntry = 0n;
  for (const { vec } of basis) for (const [c, v] of vec) {
    if (isPublic(c)) { const m = bal(v) < 0n ? -bal(v) : bal(v); if (m > maxPubEntry) maxPubEntry = m; }
  }

  return {
    ok: true,
    rank: ech.rank, free: FREE.length, nullity,
    maxRowFill: ech.maxRowLen,
    support: [...support].map((c) => idx2name.get(c) || `w[${c}]`).sort(),
    carrierClass,
    publicMovers,
    nonPublicDirCount: nonPublicDirs.length,
    nonPublicDirs,
    killedDirCount: killedDirs.length,
    maxPublicColumnEntry: maxPubEntry.toString(),
  };
}

async function main() {
  console.log(`\n=== multi-point two-witness search ===`);
  console.log(`r1cs   ${relPath(R1CS)}`);
  console.log(`points ${DIR}\n`);

  const r = readR1CS(R1CS);
  const { name2idx, idx2name } = existsSync(SYM) ? symMap(SYM) : { name2idx: new Map(), idx2name: new Map() };
  const nIn = r.nPubOut + r.nPubIn + r.nPrvIn;
  const FIXED = new Set([0]);
  for (let i = 1 + r.nPubOut; i <= nIn; i++) FIXED.add(i);
  const FREE = [];
  for (let i = 1; i < r.nWires; i++) if (!FIXED.has(i)) FREE.push(i);
  const isPublic = (i) => i >= 1 && i <= r.nPubOut;
  console.log(`wires ${r.nWires} | constraints ${r.nConstraints} | outputs ${r.nPubOut} | FREE ${FREE.length}`);
  console.log(`public signals (a null-space direction moving any of these is a soundness bug): 1..${r.nPubOut}\n`);

  const manifestPath = join(DIR, "manifest.json");
  const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, "utf8")) : null;
  const files = readdirSync(DIR).filter((f) => /^point_\d+\.json$/.test(f)).sort();
  if (!files.length) { console.error(`no point_*.json in ${DIR}; run gen_input_multipoint.mjs first`); process.exit(3); }
  console.log(`probing ${files.length} structurally diverse honest witnesses ...\n`);

  const rows = [];
  let anyRealBug = false;
  const nullitySet = new Set();
  const supportSignatures = new Set();

  for (const f of files) {
    const id = f.match(/\d+/)[0];
    const tag = manifest?.find((m) => m.id === id) || {};
    let w1;
    try { w1 = await witnessFor(join(DIR, f)); }
    catch (e) { console.log(`  ${f}  WITNESS FAILED: ${e.message.split("\n")[0]}`); rows.push({ id, ok: false, reason: "witness calculation failed" }); continue; }

    const t0 = Date.now();
    const res = analyseAtWitness(r, w1, FREE, FIXED, idx2name, isPublic);
    const dt = ((Date.now() - t0) / 1000).toFixed(1);
    if (!res.ok) { console.log(`  ${f}  ${res.reason}`); rows.push({ id, ok: false, reason: res.reason, tag }); continue; }

    nullitySet.add(res.nullity);
    const sig = res.support.join("|");
    supportSignatures.add(sig);
    if (res.publicMovers.length) anyRealBug = true;

    const shape = [
      tag.path ?? "?",
      tag.leftmost ? "leftmost" : tag.rightmost ? "rightmost" : tag.maxdepth ? "maxdepth" : "mixed",
      `sib:${tag.sib ?? "?"}`,
      `val:${tag.val ?? "?"}`,
    ].join(" ");
    const flag = res.publicMovers.length ? "  *** PUBLIC MOVER ***" : "";
    console.log(`  ${f}  nullity ${res.nullity}  rank ${res.rank}/${res.free}  killed ${res.killedDirCount}  nonpub-dirs ${res.nonPublicDirCount}  maxPubColEntry ${res.maxPublicColumnEntry}  [${shape}] ${dt}s${flag}`);
    rows.push({ id, ok: true, tag, ...res });
  }

  // ---- verdict ------------------------------------------------------
  console.log(`\n================= AGGREGATE =================`);
  console.log(`points analysed            : ${rows.filter((x) => x.ok).length} / ${files.length}`);
  console.log(`distinct nullity values    : {${[...nullitySet].sort((a, b) => a - b).join(", ")}}`);
  console.log(`distinct support signatures: ${supportSignatures.size}`);

  // classify every support signature
  const okRows = rows.filter((x) => x.ok);
  const allIsZeroInv = okRows.every((x) => x.support.every((s) => /\.isz\.inv$/.test(s)) && x.support.length === x.nullity);
  console.log(`every null-space carrier is an IsZero \`inv\` hint, at every point : ${allIsZeroInv ? "YES" : "NO"}`);

  // does the SET of freed inv hints move across points?  (expected: yes, it
  // tracks pathIndex[i] -- slot 0 frees eq[i][0].isz.inv, slot k frees eq[i][k])
  const supportsByShape = {};
  for (const x of okRows) {
    const k = x.tag?.path ?? "?";
    (supportsByShape[k] ??= new Set()).add(x.support.join("|"));
  }
  console.log(`\nnull-space support vs path shape:`);
  for (const [shape, set] of Object.entries(supportsByShape)) {
    const sample = [...set][0].split("|").map((s) => s.replace("main.mk.eq", "eq").replace(".isz.inv", "")).join(" ");
    console.log(`  ${shape.padEnd(11)} ${set.size} distinct support(s)   e.g. ${sample}`);
  }

  const spectrumClasses = new Set();
  for (const x of okRows) for (const c of x.carrierClass) spectrumClasses.add(c.pivotCoeff);
  console.log(`\npivot-coefficient classes across all carriers/points: {${[...spectrumClasses].join(", ")}}`);
  console.log(`(a carrier whose ONLY pivot is 'witness-dependent' would be the F_p analogue of a`);
  console.log(` near-zero singular value; multi-point rank stability is the test that it is not spurious)`);

  const maxAnyPubEntry = okRows.reduce((m, x) => {
    const v = BigInt(x.maxPublicColumnEntry); return v > m ? v : m;
  }, 0n);
  console.log(`\nlargest null-space entry on ANY public column, over ALL points : ${maxAnyPubEntry}`);

  writeFileSync(JSON_OUT, JSON.stringify({
    r1cs: R1CS.replace(ROOT, "").replace(/\\/g, "/").replace(/^\/+/, "") || R1CS, points: files.length,
    nullityValues: [...nullitySet], supportSignatureCount: supportSignatures.size,
    allCarriersAreIsZeroInv: allIsZeroInv,
    spectrumClasses: [...spectrumClasses],
    maxPublicColumnEntryOverAllPoints: maxAnyPubEntry.toString(),
    anyPublicMover: anyRealBug,
    rows,
  }, null, 2));
  console.log(`\nwrote ${JSON_OUT}`);

  if (anyRealBug) {
    console.log(`\n##################################################################`);
    console.log(`#  A NULL-SPACE DIRECTION MOVES A PUBLIC OUTPUT AT SOME WITNESS.   #`);
    console.log(`#  REAL SOUNDNESS BUG IN THE DEPLOYED CIRCUIT. STOP.              #`);
    console.log(`##################################################################`);
    for (const x of okRows.filter((r) => r.publicMovers.length)) {
      console.log(`  point ${x.id} [${x.tag?.path}]:`);
      for (const pm of x.publicMovers) console.log(`     anchor ${pm.anchor} moves public: ${pm.pub.join(", ")}`);
    }
    process.exit(2);
  }
  if (nullitySet.size === 1 && maxAnyPubEntry === 0n && allIsZeroInv) {
    console.log(`\nRESULT: nullity is stably ${[...nullitySet][0]} across ${okRows.length} structurally diverse`);
    console.log(`honest witnesses; every null-space direction is an IsZero \`inv\` hint; no`);
    console.log(`null-space direction has any component on any public output at any point.`);
    console.log(`\nQUANTIFIED CLAIM: no second witness with a non-zero linear component was`);
    console.log(`found at ${okRows.length} structurally diverse honest witnesses, across the full`);
    console.log(`R1CS with exact non-linear re-verification of every null-space direction.`);
    console.log(`BOUND: a second witness reachable only by a large non-linear jump with zero`);
    console.log(`linear component is outside this search.`);
    process.exit(0);
  }
  console.log(`\nRESULT: nullity or support is NOT stable across points -- see rows above.`);
  console.log(`Per after-the-oracle.md Task 1 / Falsification 2, every prior single-point`);
  console.log(`"no second witness" claim must be requalified.`);
  process.exit(1);
}

main().catch((e) => { console.error(e); process.exit(3); });
